#!/bin/sh

if [ -f /etc/mysql/change_password ]; then
  rm -f /etc/mysql/change_password

  old_password=`cat /root/.my.cnf | grep password | cut -d = -f 2`

  debian_mysql_password=`cat /etc/mysql/debian.cnf | grep password | head -n 1 | tr -d " " | cut -d = -f 2`
  new_password=`pwgen -s 16`
  sed -i "s/$debian_mysql_password/$new_password/" /etc/mysql/debian.cnf
  echo "update mysql.user set password=password('$new_password') where user = 'debian-sys-maint'; flush privileges;" | mysql -p$old_password


  new_password=`pwgen -s 16`
  echo "update mysql.user set password=password('$new_password') where user = 'root'; flush privileges;" | mysql -p$old_password

  mv /root/.my.cnf /root/.my.cnf.old

  echo "[client]" > /root/.my.cnf
  echo "password=$new_password" >> /root/.my.cnf
  chmod 700 /root/.my.cnf

fi

